### PR TITLE
Bump to 3.21.9.

### PR DESCRIPTION
**Pull request by jezdez**
Changelog: https://github.com/conda/conda-build/releases/tag/3.21.9
Changes: https://github.com/conda/conda-build/compare/3.21.8...3.21.9

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Error: HTTP 404 NOT FOUND for url <https://github.com/conda/conda-build/releases/download/3.21.9/conda-build-3.21.9.tar.gz

**Comment by jezdez** [comment]
@skupr-anaconda Used the same URL now as used in the conda feedstock. We don't upload build artifacts anymore during tagging since we moved from Azure and GitHub Actions. Not sure if that change was intentional or unintentional.

**Comment by skupr-anaconda** [comment]
An error:
```
cp: cannot stat ‘bdist_conda.py’: No such file or directory
```

**Comment by jezdez** [comment]
@skupr-anaconda Yeah, I forgot we did those changes ages ago, thanks for helping debug this :D

**Comment by jezdez** [comment]
> It's a question now of how to build it on win platforms and do not face a circular dependency introduced by conda 4.13.0 issue `ImportError: cannot import name 'itervalues' from 'conda.common.compat' ` (the fix [AnacondaRecipes/repodata-hotfixes#159](https://github.com/AnacondaRecipes/repodata-hotfixes/pull/159)).

I think this could be built with conda < 4.13 in the environment without triggering the import error.

**Comment by dbast** [comment]
seems like we have to start a new windows agent with a newer AMI version, that was created after the repo data fix got in place.

**Comment by dbast** [comment]
the windows AMI was created after the repo data hotfix, but still it contains conda 4.13 + conda-build 4.21.8. This should prevent it https://github.com/AnacondaRecipes/repodata-hotfixes/pull/159/files

**Comment by skupr-anaconda** [comment]
conda-build 3.21.9 is available on defaults

**Pull request merged**
