### PR TITLE
Remove upstreamed patch

### PR DESCRIPTION
**Pull request by isuruf**
conda-build was applying the reverse patch

### CODE REVIEW

**Review by mingwandroid — APPROVED** [review]

**Comment by mingwandroid** [comment]
Thanks @isuruf!

**Comment by mingwandroid** [comment]
Are you sure that the package was bad and that it wasn't just the reversion messages that made it look that way? conda-build could/should learn to error out when it finds a patch already applied I think.

**Comment by isuruf** [comment]
Yes. I looked at the 3.20.2 package from defaults and it had the line https://github.com/AnacondaRecipes/conda-build-feedstock/blob/master/recipe/gh3606.patch#L21 which is not in the original 3.20.2 source.

**Comment by mingwandroid** [comment]
OK, I'll reopen the bug then.

**Pull request merged**
